import { Room, Team, Participant, User } from './types';

export const INITIAL_ROOM: Room = {
  id: 'room-badminton-camp',
  code: 'CLASS-42',
  name: 'Lớp Cầu Lông Badminton Camp',
  activity: 'Quản lý Ngày học & Sân tập',
  lastUpdated: 'Vừa xong',
  totalParticipants: 24,
};

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    number: 1,
    name: 'Level 0 - Kiệt',
    lead: {
      id: 'lead-1',
      name: 'Kiệt',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      badgeTitle: 'Level 0 (0)',
    },
    colorScheme: {
      id: 'unified-gold',
      name: 'Standard Gold',
      headerBg: 'bg-[#FAF7F2]',
      headerBorder: 'border-[#E6DFD3]',
      headerText: 'text-[#1B2A3E]',
      headerBadgeText: 'text-[#1B2A3E]',
      leadBannerBg: 'bg-[#D9B472] text-[#1B2A3E] font-bold',
      leadAvatarBg: 'bg-[#EFE7D8] text-[#1B2A3E]',
      leadAvatarText: 'text-[#1B2A3E]',
      badgeBg: 'bg-[#EFE7D8] text-[#1B2A3E] border border-[#E6DFD3]',
      badgeText: 'text-[#1B2A3E]',
      borderAccent: 'border-[#E6DFD3]',
      accentBg: 'bg-amber-50/40',
      avatarBg: 'bg-[#1B2A3E] text-white',
      avatarText: 'text-white',
      dotColor: 'bg-[#D9B472]',
    },
  },
  {
    id: 'team-2',
    number: 2,
    name: 'Level 1 - Duy',
    lead: {
      id: 'lead-3',
      name: 'Duy',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      badgeTitle: 'Level 1 (1)',
    },
    colorScheme: {
      id: 'unified-gold',
      name: 'Standard Gold',
      headerBg: 'bg-[#FAF7F2]',
      headerBorder: 'border-[#E6DFD3]',
      headerText: 'text-[#1B2A3E]',
      headerBadgeText: 'text-[#1B2A3E]',
      leadBannerBg: 'bg-[#D9B472] text-[#1B2A3E] font-bold',
      leadAvatarBg: 'bg-[#EFE7D8] text-[#1B2A3E]',
      leadAvatarText: 'text-[#1B2A3E]',
      badgeBg: 'bg-[#EFE7D8] text-[#1B2A3E] border border-[#E6DFD3]',
      badgeText: 'text-[#1B2A3E]',
      borderAccent: 'border-[#E6DFD3]',
      accentBg: 'bg-amber-50/40',
      avatarBg: 'bg-[#1B2A3E] text-white',
      avatarText: 'text-white',
      dotColor: 'bg-[#D9B472]',
    },
  },
  {
    id: 'team-3',
    number: 3,
    name: 'Level 2 - Phát',
    lead: {
      id: 'lead-4',
      name: 'Phát',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80',
      badgeTitle: 'Level 2 (2)',
    },
    colorScheme: {
      id: 'unified-gold',
      name: 'Standard Gold',
      headerBg: 'bg-[#FAF7F2]',
      headerBorder: 'border-[#E6DFD3]',
      headerText: 'text-[#1B2A3E]',
      headerBadgeText: 'text-[#1B2A3E]',
      leadBannerBg: 'bg-[#D9B472] text-[#1B2A3E] font-bold',
      leadAvatarBg: 'bg-[#EFE7D8] text-[#1B2A3E]',
      leadAvatarText: 'text-[#1B2A3E]',
      badgeBg: 'bg-[#EFE7D8] text-[#1B2A3E] border border-[#E6DFD3]',
      badgeText: 'text-[#1B2A3E]',
      borderAccent: 'border-[#E6DFD3]',
      accentBg: 'bg-amber-50/40',
      avatarBg: 'bg-[#1B2A3E] text-white',
      avatarText: 'text-white',
      dotColor: 'bg-[#D9B472]',
    },
  },
  {
    id: 'team-4',
    number: 4,
    name: 'Level 3 - Tú',
    lead: {
      id: 'lead-2',
      name: 'Tú',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
      badgeTitle: 'Level 3 (3)',
    },
    colorScheme: {
      id: 'unified-gold',
      name: 'Standard Gold',
      headerBg: 'bg-[#FAF7F2]',
      headerBorder: 'border-[#E6DFD3]',
      headerText: 'text-[#1B2A3E]',
      headerBadgeText: 'text-[#1B2A3E]',
      leadBannerBg: 'bg-[#D9B472] text-[#1B2A3E] font-bold',
      leadAvatarBg: 'bg-[#EFE7D8] text-[#1B2A3E]',
      leadAvatarText: 'text-[#1B2A3E]',
      badgeBg: 'bg-[#EFE7D8] text-[#1B2A3E] border border-[#E6DFD3]',
      badgeText: 'text-[#1B2A3E]',
      borderAccent: 'border-[#E6DFD3]',
      accentBg: 'bg-amber-50/40',
      avatarBg: 'bg-[#1B2A3E] text-white',
      avatarText: 'text-white',
      dotColor: 'bg-[#D9B472]',
    },
  },
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  // Team 1 members (Kiệt - Level 0)
  { id: 'p-minh', name: 'Nguyễn Văn Minh', studentCode: 'SV01', status: 'present', teamId: 'team-1', level: 0 },
  { id: 'p-an', name: 'Trần Hoài An', studentCode: 'SV02', status: 'present', teamId: 'team-1', level: 0 },
  { id: 'p-long', name: 'Lê Hoàng Long', studentCode: 'SV03', status: 'present', teamId: 'team-1', level: 0 },
  { id: 'p-huy', name: 'Phạm Quang Huy', studentCode: 'SV04', status: 'present', teamId: 'team-1', level: 0 },
  { id: 'p-khoa', name: 'Đỗ Đăng Khoa', studentCode: 'SV05', status: 'present', teamId: 'team-1', level: 0 },
  { id: 'p-john', name: 'Ngô Thành Đạt', studentCode: 'SV06', status: 'present', teamId: 'team-1', level: 0 },

  // Team 2 members (Duy - Level 1)
  { id: 'p-nam', name: 'Hoàng Hải Nam', studentCode: 'SV07', status: 'present', teamId: 'team-2', level: 0 },
  { id: 'p-phuc', name: 'Vũ Đức Phúc', studentCode: 'SV08', status: 'present', teamId: 'team-2', level: 0 },
  { id: 'p-tung', name: 'Bùi Thanh Tùng', studentCode: 'SV09', status: 'present', teamId: 'team-2', level: 0 },
  { id: 'p-vy', name: 'Nguyễn Thảo Vy', studentCode: 'SV10', status: 'present', teamId: 'team-2', level: 0 },
  { id: 'p-linh', name: 'Trịnh Khánh Linh', studentCode: 'SV11', status: 'present', teamId: 'team-2', level: 0 },
  { id: 'p-peter', name: 'Lê Phúc Thịnh', studentCode: 'SV12', status: 'present', teamId: 'team-2', level: 0 },

  // Team 3 members (Phát - Level 2)
  { id: 'p-quang', name: 'Đinh Nhật Quang', studentCode: 'SV13', status: 'present', teamId: 'team-3', level: 0 },
  { id: 'p-bao', name: 'Lâm Gia Bảo', studentCode: 'SV14', status: 'present', teamId: 'team-3', level: 0 },
  { id: 'p-trang', name: 'Phan Thu Trang', studentCode: 'SV15', status: 'present', teamId: 'team-3', level: 0 },
  { id: 'p-nhi', name: 'Hồ Yến Nhi', studentCode: 'SV16', status: 'present', teamId: 'team-3', level: 0 },
  { id: 'p-alice', name: 'Nguyễn Ngọc Anh', studentCode: 'SV17', status: 'present', teamId: 'team-3', level: 0 },
  { id: 'p-jenny', name: 'Hoàng Kim Ngân', studentCode: 'SV18', status: 'absent', note: 'Có phép', teamId: 'team-3', level: 0 },

  // Team 4 members (Tú - Level 3)
  { id: 'p-khanh', name: 'Mai Quốc Khánh', studentCode: 'SV19', status: 'present', teamId: 'team-4', level: 0 },
  { id: 'p-tuan', name: 'Đặng Anh Tuấn', studentCode: 'SV20', status: 'present', teamId: 'team-4', level: 0 },
  { id: 'p-mai', name: 'Lý Tuyết Mai', studentCode: 'SV21', status: 'present', teamId: 'team-4', level: 0 },
  { id: 'p-ha', name: 'Dương Thu Hà', studentCode: 'SV22', status: 'present', teamId: 'team-4', level: 0 },
  { id: 'p-harry', name: 'Trương Minh Trí', studentCode: 'SV23', status: 'present', teamId: 'team-4', level: 0 },
  { id: 'p-tom', name: 'Phạm Đức Duy', studentCode: 'SV24', status: 'absent', note: 'Vắng không phép', teamId: 'team-4', level: 0 },
];

export const INITIAL_USER: User = {
  id: 'user-host',
  name: 'Alex Rivera',
  email: 'alex.organizer@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'host',
};
